# Generated by Django 4.0.5 on 2023-06-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio del Producto')),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('idVenta', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Venta')),
                ('productosVendidos', models.CharField(max_length=50, verbose_name='Nombre de los Productos')),
                ('totalVenta', models.IntegerField(verbose_name='Precio final de compra')),
            ],
        ),
    ]
