# Generated by Django 4.0.5 on 2023-06-23 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('serie', models.IntegerField(primary_key=True, serialize=False, verbose_name='Serie Producto')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca del Producto')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo del Producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('fecha', models.DateTimeField(verbose_name='Fecha del Producto')),
                ('valor', models.IntegerField(verbose_name='Precio del Producto')),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('idVenta', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Venta')),
                ('totalVenta', models.IntegerField(verbose_name='Precio final de compra')),
                ('productosVendidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productos')),
            ],
        ),
    ]
